language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpulse-dev libasound2-dev pulseaudio doxygen
script: autoreconf -i && ./configure && make check
